name: Deploy Landing Page

permissions:
  contents: write

on:
  push:
    branches: [main]
    paths:
      - "landing_page/**"
      - ".github/workflows/deploy-landing.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Check commit message
        id: check
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $MESSAGE"

          if [[ "$MESSAGE" != *"deploy:landing"* ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi


      - name: Setup Node
        if: steps.check.outputs.skip == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Cache node modules
        if: steps.check.outputs.skip == 'false'
        uses: actions/cache@v4
        with:
          path: landing_page/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('landing_page/package-lock.json') }}


      - name: Install dependencies
        if: steps.check.outputs.skip == 'false'
        working-directory: landing_page
        run: npm install


      - name: Build Next.js
        if: steps.check.outputs.skip == 'false'
        working-directory: landing_page
        run: npm run build


      - name: Deploy to GitHub Pages
        if: steps.check.outputs.skip == 'false'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: landing_page/out